services:
  postgres:
    image: postgres:15
    container_name: postgres-r2dbc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: testdb
      MB_DB_PORT: 5432
      MB_DB_USER: testuser
      MB_DB_PASS: testpass
      MB_DB_HOST: postgres
    depends_on:
      - postgres

volumes:
  pgdata: